### GENERAL SETTINGS ###

# Site settings
title: "cyanoScope: Citizen Science, Microscopy, and Cyanobacteria"
description: "This is the project page for the cyanoScope project.  We are developing tools and protocols to gain an understanding of where different cyanobacteria taxa are known to occur."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://cyanoscope.org"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
#social:
#  - title: dribbble
#    url:
#  - title: facebook
#    url:
#  - title: twitter
#    url:
#  - title: instagram
#    url:
#  - title: tumblr
#    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
#address:
#  - lines:
#email: info@cyanoscope.org
#tel:


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Bryan Milstead
    position: "Research Ecologist, Atlantic Ecology Division"
    text:
    img:
    social:
      - title: envelope #use for email address
        url: mailto:milstead.bryan@epa.gov
      - title:
        url:
  - name: Jeffrey Hollister
    position: "Research Ecologist, Atlantic Ecology Division"
    text:
    img:
    social:
      - title: envelope #use for email address
        url: mailto:hollister.jeff@epa.gov
      - title: twitter
        url: http://twitter.com/jhollist
  - name: Betty Kreakie
    position: "Research Ecologist, Atlantic Ecology Division"
    text:
    img:
    social:
      - title: envelope #use for email address
        url: mailto:kreakie.betty@epa.gov
      - title:
        url:
  - name: Hilary Snook
    position: "Senior Environmental Scientist, EPA Region 1 Lab"
    text:
    img:
    social:
     - title: envelope #use for email address
        url: mailto:snook.hilary@epa.gov
      - title:
        url:
  - name: Tom Hollenhorst
    position: "Research Ecologist, Mid-continent Ecology Division"
    text:
    img:
    social:
      - title: envelope #use for email address
        url: mailto:hollenhorst.tom@epa.gov
      - title:
        url:

# Clients information. Shown on Home and About pages.
#clients:
#  - name:
#    img:
#  - name:
#    img:
#  - name:
#    img:
#  - name:
#    img:

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
#about: "Citizen Science, Microscopy, and Cyanobacteria "

# Testimonial content. Shown on Home and About page.
#testimonial:
#    message:
#    author:
#    position: